### PR TITLE
Update Writing-Servers.md

### PR DESCRIPTION
**Pull request by joshmutus**
Added link to types page in relevant place on page

### CODE REVIEW

**Comment by DanielSank** [comment]
LGTM

**Comment by joshmutus** [comment]
Uhm. How to merge?

**Comment by jayich** [comment]
My merge comment is not easily seen:  merged because @DanielSank gave the okay.

**Comment by DanielSank** [comment]
@jayich please don't merge other people's PRs.

**Comment by jayich** [comment]
@DanielSank, sorry, can you clarify the merge procedure.  I did this because I thought @joshmutus could not merge.

**Comment by DanielSank** [comment]
I need to post real contribution guidelines. It's on my todo list.

**Pull request merged**
